### ISSUE TITLE
slab_glass_1 becames transperent from medium distance when mipmapping is on

### ISSUE THREAD

**Issue by Fixer-007** [minetest-mods/moreblocks#33] opened 2016-02-19 22:32 UTC
It clearly looks like mip-mapping causes slab_glass_1 to became transparent from some medium distance, but for some reason yellow slab_super_glow_glass_1 is not affected.

Can be observed on Liberty Land at 92 5 47

Screenshots:
https://i.imgur.com/uXuw3xf.png (closer)
https://i.imgur.com/hJ6vD04.png (further)

Config: http://pastebin.com/raw/fLgAQtNw

Not sure if it is core bug or moreblocks one. Observing it with minetest git 5dbaa68
Videoadapter: AMD/ATi Radeon HD 6870 / OGL 4.5 / Win 7sp1

**Comment by sofar** [comment] 2016-02-20 20:13
Can't reproduce with NVIDIA/Linux/OGL4.5

slab_glass_1 and yellow_slab_super_glow_glass_1 used. Mipmapping enabled. I can see mipmapping at exactly the same distance affect both nodes the same way.

**Comment by sofar** [comment] 2016-02-20 20:16
Totally can see it on "Liberty Land" as well, though!

**Comment by sofar** [comment] 2016-02-20 20:25
I wonder if the server is outdated and/or have culling set. In any case, I doubt this is a moreblocks bug.

**Comment by Fixer-007** [comment] 2016-02-20 23:09
Server owner said it is updated (manually).

**Comment by sofar** [comment] 2016-03-20 05:48
Closing for now. I highly doubt this has anything to do with moreblocks. If you feel like it, open a bug against minetest instead.

**Closed by sofar** 2016-03-20 05:48 UTC
