### ISSUE TITLE
Moreblocks breaks dark green wool recipe/craft

### ISSUE THREAD

**Issue by VanessaE** [minetest-mods/moreblocks#130] opened 2018-10-16 16:07 UTC
Trying to craft dark green wool using dark green dye and white wool gives the brighter green wool.

To make sure it wasn't some other mod, I wiped out ~/.minetest/mods, copied moreblocks to there, and enabled it on a test world.  The result:

![image](https://user-images.githubusercontent.com/1733537/47030128-14615980-d13b-11e8-8ad4-f12386a79c17.png)

That is most assuredly dark green dye on the left, and bright green wool as the output.

Engine: stable-0.4 branch, commit https://github.com/minetest/minetest/commit/dd5f03731ad545f52da24825a2ee870f899f6adc
minetest_game: stable-0.4 branch,  commit https://github.com/minetest/minetest_game/commit/d6a66860af6fc39957d8e947824b9c56c3686b8e
moreblocks:  commit 723db44933721cc14e85ec40ada5ae5e936cb7d7
No other mods enabled in the test world.

**Comment by JDCodeIt** [comment] 2019-03-26 12:54
This seems to be a weird side effect of the call to minetest.clear_craft. The bug was introduced with https://github.com/minetest-mods/moreblocks/pull/124

If you comment out this in redefinitions.lua, the dark_green wool recipe works.

This could be a deeper bug in the clear_craft function, though.

**Comment by JDCodeIt** [comment] 2019-03-26 19:01
In irc discussion today, p_gimeno found the root cause is in this version of minetest game, which essentially has created two recipes with the same input. One produces green wool, and the other produces dark green wool. The order of these recipes in the system were such that the dark green (proper) recipe occurred first. Calling the clear_craft function has the side effect of inverting the list of registered recipes so that the lighter green recipe came first.
MTG has been updated to remove the duplicate recipe input. See https://github.com/minetest/minetest_game/commits/6f80fd3737cd4de30e548dd48bc0ab8c288d9930

Thanks p_gimeno!

**Comment by Calinou** [comment] 2019-03-26 20:11
Is this issue now solved (if so, in which stable Minetest versions)?

**Comment by pgimeno** [comment] 2019-03-27 00:08
Technically it's solved in MTG 5.0.0. See also https://github.com/minetest/minetest/issues/8427 for the remaining bug.

**Comment by Calinou** [comment] 2019-03-27 12:28
@pgimeno Thanks for clarifying this :smiley: I'll close this issue now.

**Closed by Calinou** 2019-03-27 12:28 UTC
